name=NeuWiFi
version=1.0.0
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=A high-performance native WiFi library for ESP32.
paragraph=NeuWiFi is built directly on top of ESP-IDF, providing a cleaner and more efficient alternative to the standard Arduino WiFi library. It supports Station, Access Point, and Hybrid modes with a modular architecture.
category=Communication
url=https://github.com/ulywae/NeuWiFi
architectures=esp32
includes=NeuWiFi.h